# Generated by Django 6.1 on 2026-08-29 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cnae',
            fields=[
                ('codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj_basico', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('razao_social', models.CharField(max_length=200)),
                ('capital_social', models.DecimalField(decimal_places=2, max_digits=15)),
                ('porte_empresa', models.CharField(blank=True, max_length=2)),
                ('ente_federativo_responsavel', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Motivo',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NaturezaJuridica',
            fields=[
                ('codigo', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Qualificacao',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj_ordem', models.CharField(max_length=4)),
                ('cnpj_dv', models.CharField(max_length=2)),
                ('identificador_matriz_filial', models.CharField(max_length=1)),
                ('nome_fantasia', models.CharField(blank=True, max_length=200)),
                ('situacao_cadastral', models.CharField(max_length=2)),
                ('data_situacao_cadastral', models.DateField(null=True)),
                ('data_inicio_atividade', models.DateField(null=True)),
                ('cnae_secundaria', models.CharField(blank=True, max_length=1000)),
                ('tipo_logradouro', models.CharField(blank=True, max_length=30)),
                ('logradouro', models.CharField(blank=True, max_length=200)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=200)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cep', models.CharField(blank=True, max_length=8)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('cnae_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cnpj.cnae')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estabelecimentos', to='cnpj.empresa')),
                ('motivo_situacao_cadastral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.motivo')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.municipio')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='natureza_juridica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.naturezajuridica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='qualificacao_responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cnpj.qualificacao'),
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador_socio', models.CharField(max_length=1)),
                ('nome_socio', models.CharField(max_length=200)),
                ('cpf_cnpj_socio', models.CharField(blank=True, max_length=14)),
                ('data_entrada_sociedade', models.DateField(null=True)),
                ('pais', models.CharField(blank=True, max_length=3)),
                ('representante_legal', models.CharField(blank=True, max_length=14)),
                ('nome_representante', models.CharField(blank=True, max_length=200)),
                ('faixa_etaria', models.CharField(blank=True, max_length=1)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socios', to='cnpj.empresa')),
                ('qualificacao_representante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cnpj.qualificacao')),
                ('qualificacao_socio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cnpj.qualificacao')),
            ],
        ),
    ]
